const API='https://lwamaovuxcevsjfvtqhf.supabase.co/rest/v1/rpc/';
const KEY='sb_publishable_j0O_u0t7-lDCtBbmqaIz3A_8vAIGcyJ';
const SLUG='einstein-ia-a06-2026-2';
const TOKEN_KEY='tbl-host:'+SLUG;
const letters=['A','B','C','D'];
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function rpc(fn,body){const r=await fetch(API+fn,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.message||'Falha no painel.');return data}
let token=sessionStorage.getItem(TOKEN_KEY)||'',refreshing=false;
function clock(n){n=Math.max(0,Number(n)||0);return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
function bars(data,title){const total=(data||[]).reduce((s,x)=>s+x.votes,0);return `<h3>${esc(title)}</h3><div class="bars">${(data||[]).map(x=>`<div class="barrow"><span class="letter">${letters[x.choice]}</span><div class="bartrack"><div class="barfill" style="width:${total?100*x.votes/total:0}%"></div></div><span class="barvalue">${x.votes} · ${total?Math.round(100*x.votes/total):0}%</span></div>`).join('')}</div>`}
function caseView(s){return `<p class="eyebrow">Caso em projeção</p><h2>${esc(s.case_title)}</h2><p class="case">${esc(s.case_text)}</p><div class="options">${s.options.map(o=>`<article class="option"><span class="letter">${o.letter}</span><span><h3>${esc(o.title)}</h3><p>${esc(o.text)}</p><span class="tradeoffs"><span class="gain">Potencial: ${esc(o.gain)}</span><span class="cost">Custo: ${esc(o.cost)}</span></span></span></article>`).join('')}</div>`}
function story(s){const t=s.transitions||[],total=t.reduce((a,x)=>a+x.people,0),stayed=t.filter(x=>x.from_choice===x.to_choice).reduce((a,x)=>a+x.people,0),moved=total-stayed,lead=[...t].filter(x=>x.from_choice!==x.to_choice).sort((a,b)=>b.people-a.people)[0];return `${bars(s.round1,'Rodada 1')}${bars(s.round2,'Rodada 2')}<h2>O argumento moveu a sala</h2><div class="story-grid"><div class="story"><span class="number">${total}</span>duas decisões registradas</div><div class="story"><span class="number">${stayed}</span>posições sustentadas</div><div class="story"><span class="number">${moved}</span>posições revistas</div></div><p class="lead">${lead?`A principal corrente foi <strong>${letters[lead.from_choice]} → ${letters[lead.to_choice]}</strong>, com ${lead.people} ${lead.people===1?'pessoa':'pessoas'}. Pergunte o que mudou: a ordem do processo, a confiança nos dados, o prazo ou o papel atribuído à IA?`:'Ainda não há uma corrente de mudança entre alternativas.'}</p><div class="transition-list">${t.sort((a,b)=>b.people-a.people).map(x=>`<div class="transition"><span>${letters[x.from_choice]} → ${letters[x.to_choice]} ${x.from_choice===x.to_choice?'· sustentou':'· reconsiderou'}</span><strong>${x.people}</strong></div>`).join('')}</div>`}
function render(s){$('#participants').textContent=s.participants;$('#phase').textContent=({lobby:'Lobby',round1:'Rodada 1',discussion:'Discussão',round2:'Rodada 2',reveal:'Revelação'})[s.phase]||s.phase;$('#timer').textContent=s.phase==='lobby'?'--:--':clock(s.remaining);$('#phase-title').textContent=({lobby:'Sala em formação',round1:'Decisão individual',discussion:'Arquitetura em debate',round2:'Reconsideração individual',reveal:'Drift das escolhas'})[s.phase];let html=caseView(s);if(s.phase==='discussion'||s.phase==='round2')html=`${bars(s.round1,'Primeira rodada')}${s.phase==='discussion'?'<div class="prompt"><strong>Pergunta para circular pela sala</strong><p>Qual hipótese precisa ser verdadeira para sua alternativa funcionar — e como você a testaria antes da reunião do conselho?</p></div>':''}`;if(s.phase==='reveal')html=story(s);$('#host-content').innerHTML=html;$('#roster').innerHTML=`<table><thead><tr><th>Participante</th><th>Rodada 1</th><th>Rodada 2</th></tr></thead><tbody>${s.roster.map(p=>`<tr><td>${esc(p.name)}</td><td>${p.r1==null?'—':letters[p.r1]}</td><td>${p.r2==null?'—':letters[p.r2]}</td></tr>`).join('')}</tbody></table>`}
async function refresh(){if(!token||refreshing)return;refreshing=true;try{const s=await rpc('tbl_host_state',{p_slug:SLUG,p_token:token});render(s);$('#auth').classList.add('hidden');$('#dashboard').classList.remove('hidden')}catch(e){$('#auth-message').textContent=e.message;sessionStorage.removeItem(TOKEN_KEY)}finally{refreshing=false}}
$('#token-form').addEventListener('submit',e=>{e.preventDefault();token=$('#token').value;sessionStorage.setItem(TOKEN_KEY,token);refresh()});
document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',async()=>{const action=b.dataset.action;if((action==='clear'||action==='start')&&!confirm(action==='clear'?'Limpar participantes e votos desta sala?':'Iniciar uma nova sequência e apagar os votos anteriores?'))return;$('#host-message').textContent='Atualizando a sala…';try{const s=await rpc('tbl_host',{p_slug:SLUG,p_token:token,p_action:action});render(s);$('#host-message').textContent=action==='start'?'Sequência iniciada: 100 s + 10 min + 100 s.':'Sala atualizada.'}catch(e){$('#host-message').textContent=e.message}}));
const studentUrl=new URL('index.html',location.href).href;$('#student-url').textContent=studentUrl;$('#copy-link').addEventListener('click',async()=>{await navigator.clipboard.writeText(studentUrl);$('#copy-link').textContent='Link copiado ✓';setTimeout(()=>$('#copy-link').textContent='Copiar link',1600)});
if(token){$('#token').value=token;refresh()}setInterval(refresh,2000);
