const API='https://lwamaovuxcevsjfvtqhf.supabase.co/rest/v1/rpc/';
const KEY='sb_publishable_j0O_u0t7-lDCtBbmqaIz3A_8vAIGcyJ';
const SLUG='einstein-ia-a06-2026-2';
const STORAGE='tbl:'+SLUG;
const letters=['A','B','C','D'];
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function rpc(fn,body){const r=await fetch(API+fn,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.message||'Não foi possível acessar a sala.');return data}
let person=null,lastPhase='',busy=false;
try{person=JSON.parse(localStorage.getItem(STORAGE))}catch{}
function clock(n){n=Math.max(0,Number(n)||0);return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
function bars(data,title){const total=(data||[]).reduce((s,x)=>s+x.votes,0);return `<h3>${esc(title)}</h3><div class="bars">${(data||[]).map(x=>`<div class="barrow"><span class="letter">${letters[x.choice]}</span><div class="bartrack"><div class="barfill" style="width:${total?100*x.votes/total:0}%"></div></div><span class="barvalue">${x.votes} · ${total?Math.round(100*x.votes/total):0}%</span></div>`).join('')}</div>`}
function caseBlock(s,round){const chosen=s.mine?.['round'+round];return `<div class="panel"><p class="eyebrow">Caso financeiro</p><h2>${esc(s.case_title)}</h2><p class="case">${esc(s.case_text)}</p></div><div class="options">${s.options.map((o,i)=>`<button class="option ${chosen===i?'selected':''}" data-choice="${i}"><span class="letter">${esc(o.letter)}</span><span><h3>${esc(o.title)}</h3><p>${esc(o.text)}</p><span class="tradeoffs"><span class="gain">Potencial: ${esc(o.gain)}</span><span class="cost">Custo: ${esc(o.cost)}</span></span></span></button>`).join('')}</div>`}
function story(s){const t=s.transitions||[],total=t.reduce((a,x)=>a+x.people,0),stayed=t.filter(x=>x.from_choice===x.to_choice).reduce((a,x)=>a+x.people,0),moved=total-stayed;const lead=[...t].filter(x=>x.from_choice!==x.to_choice).sort((a,b)=>b.people-a.people)[0];return `${bars(s.round1,'Antes da discussão')}${bars(s.round2,'Depois da discussão')}<h3>A história da mudança</h3><div class="story-grid"><div class="story"><span class="number">${total}</span>completaram as duas rodadas</div><div class="story"><span class="number">${stayed}</span>mantiveram sua arquitetura</div><div class="story"><span class="number">${moved}</span>mudaram de posição</div></div><p class="case">${lead?`O deslocamento mais frequente foi de <strong>${letters[lead.from_choice]}</strong> para <strong>${letters[lead.to_choice]}</strong>, com ${lead.people} ${lead.people===1?'pessoa':'pessoas'}. A mudança registra persuasão, dúvida ou nova prioridade; ela não transforma a alternativa escolhida em gabarito.`:'A turma preservou suas escolhas ou ainda não completou as duas rodadas.'}</p><div class="transition-list">${t.sort((a,b)=>b.people-a.people).map(x=>`<div class="transition"><span>${letters[x.from_choice]} → ${letters[x.to_choice]} ${x.from_choice===x.to_choice?'· permaneceu':'· mudou'}</span><strong>${x.people}</strong></div>`).join('')}</div>`}
function render(s){$('#participants').textContent=s.participants;$('#phase').textContent=({lobby:'Lobby',round1:'Rodada 1',discussion:'Discussão',round2:'Rodada 2',reveal:'Deslocamento'})[s.phase]||s.phase;$('#timer').textContent=s.phase==='lobby'?'--:--':clock(s.remaining);const titles={lobby:'Aguardando o professor',round1:'Escolha sua arquitetura inicial',discussion:'Defenda, ataque e reconstrua',round2:'Escolha novamente',reveal:'O que mudou na sala?'};$('#phase-title').textContent=titles[s.phase]||'Sala TBL';let html='';if(s.phase==='lobby')html='<p class="lead">Você já está na sala. A atividade começa quando o professor liberar a primeira rodada.</p>';if(s.phase==='round1')html=caseBlock(s,1);if(s.phase==='discussion')html=`<div class="discussion"><div>${bars(s.round1,'Distribuição da primeira rodada')}</div><div><h3>10 minutos de investigação</h3><div class="prompt"><strong>1. Processo</strong><p>Qual etapa vem antes da próxima e quem responde por ela?</p></div><div class="prompt"><strong>2. Dados</strong><p>Qual é o grão mínimo da base e como os totais serão reconciliados?</p></div><div class="prompt"><strong>3. IA e apresentação</strong><p>Onde a IA agrega velocidade, onde pode inventar segurança e qual evidência acompanha cada cenário?</p></div><div class="prompt"><strong>Regra do debate</strong><p>Explique primeiro o custo da sua própria alternativa; depois questione a prioridade da alternativa vizinha.</p></div></div></div>`;if(s.phase==='round2')html=`<div class="panel"><p class="eyebrow">Reconsideração</p><h2>O que a discussão alterou no seu critério?</h2><p class="case">Vote outra vez. Você pode manter sua escolha ou mudar. A distribuição desta rodada permanece oculta até a revelação.</p></div>${caseBlock(s,2)}`;if(s.phase==='reveal')html=story(s);$('#content').innerHTML=html;if(s.phase==='round1'||s.phase==='round2')document.querySelectorAll('[data-choice]').forEach(b=>b.addEventListener('click',()=>vote(s.phase==='round1'?1:2,+b.dataset.choice)));lastPhase=s.phase}
async function vote(round,choice){if(busy)return;busy=true;$('#message').textContent='Registrando sua decisão…';try{await rpc('tbl_vote',{p_slug:SLUG,p_id:person.id,p_round:round,p_choice:choice});$('#message').textContent=`Escolha ${letters[choice]} registrada. Você pode alterá-la enquanto o tempo estiver aberto.`;await refresh()}catch(e){$('#message').textContent=e.message}finally{busy=false}}
async function refresh(){if(!person)return;try{const s=await rpc('tbl_state',{p_slug:SLUG,p_id:person.id});render(s);$('#room').classList.remove('hidden');$('#join-panel').classList.add('hidden');$('#welcome').textContent=`${person.name} · sua sessão está ativa`}catch(e){$('#message').textContent=e.message}}
$('#join-form').addEventListener('submit',async e=>{e.preventDefault();const name=$('#name').value.trim();const id=person?.id||crypto.randomUUID();$('#join-message').textContent='Entrando…';try{person=await rpc('tbl_enter',{p_slug:SLUG,p_id:id,p_name:name});localStorage.setItem(STORAGE,JSON.stringify(person));await refresh()}catch(err){$('#join-message').textContent=err.message}});
if(person){$('#name').value=person.name;rpc('tbl_enter',{p_slug:SLUG,p_id:person.id,p_name:person.name}).then(()=>refresh()).catch(()=>{person=null;localStorage.removeItem(STORAGE)})}
setInterval(refresh,2000);

